mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
global-client-fingerprint: chrome
unified-delay: true
tcp-concurrent: true
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
  - system
  - 119.29.29.29
  - 223.5.5.5
  - 114.114.114.114
  - 2400:3200::1
  nameserver:
  - https://223.5.5.5/dns-query#skip-cert-verify=true
  - https://doh.pub/dns-query#skip-cert-verify=true
  - https://dns.alidns.com/dns-query#skip-cert-verify=true
  - tls://223.5.5.5#skip-cert-verify=true
  - tls://dot.pub#skip-cert-verify=true
  - tls://dns.alidns.com#skip-cert-verify=true
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query#skip-cert-verify=true
  - https://doh.pub/dns-query#skip-cert-verify=true
  - https://dns.alidns.com/dns-query#skip-cert-verify=true
  - tls://223.5.5.5#skip-cert-verify=true
  - tls://dot.pub#skip-cert-verify=true
  - tls://dns.alidns.com#skip-cert-verify=true
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - '*.time.edu.cn'
  - '*.ntp.org.cn'
  - +.pool.ntp.org
  - time1.cloud.tencent.com
  - stun.*.*
  - stun.*.*.*
  - swscan.apple.com
  - mesu.apple.com
  - music.163.com
  - '*.music.163.com'
  - '*.126.net'
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - '*.kuwo.cn'
  - api-jooxtt.sanook.com
  - api.joox.com
  - y.qq.com
  - '*.y.qq.com'
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - localhost.ptlogin2.qq.com
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - music.migu.cn
  - +.wotgame.cn
  - +.wggames.cn
  - +.wowsgame.cn
  - +.wargaming.net
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - xbox.*.*.microsoft.com
  - '*.*.xboxlive.com'
  - '*.ipv6.microsoft.com'
  - teredo.*.*.*
  - teredo.*.*
  - speedtest.cros.wr.pvp.net
  - +.jjvip8.com
  - www.douyu.com
  - activityapi.huya.com
  - activityapi.huya.com.w.cdngslb.com
  - www.bilibili.com
  - api.bilibili.com
  - a.w.bilicdn1.com
proxies:
- name: 流量已耗尽，请登录官网购买重置包。
  type: ss
  server: 127.0.0.1
  port: 1
  cipher: aes-128-gcm
  password: password
  udp: true
proxy-groups:
- name: 三毛机场
  type: select
  proxies:
  - ♻️ 自动选择
  - 流量已耗尽，请登录官网购买重置包。
  url: http://www.apple.com/library/test/success.html
  interval: 1800
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - 流量已耗尽，请登录官网购买重置包。
  url: http://www.apple.com/library/test/success.html
  interval: 1800
rules:
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,192.168.191.0/24,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- DOMAIN-KEYWORD,rhodes-island,DIRECT
- DOMAIN-KEYWORD,picacomic,三毛机场
- DOMAIN-KEYWORD,dynv6,DIRECT
- DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,DIRECT
- DOMAIN-SUFFIX,steamcontent.com,DIRECT
- DOMAIN-SUFFIX,steamusercontent.com,DIRECT
- DOMAIN-SUFFIX,steamstatic.com,DIRECT
- DOMAIN-SUFFIX,steamgames.com,DIRECT
- DOMAIN-SUFFIX,steampowered.com,DIRECT
- DOMAIN,media.steampowered.com,DIRECT
- DOMAIN,content.steampowered.com,DIRECT
- DOMAIN,client-download.steampowered.com,DIRECT
- DOMAIN,steamcdn-a.akamaihd.net,DIRECT
- DOMAIN-SUFFIX,steamserver.net,DIRECT
- DOMAIN,injections.adguard.org,DIRECT
- DOMAIN,local.adguard.org,DIRECT
- IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,192.0.0.0/24,DIRECT,no-resolve
- IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
- IP-CIDR,192.88.99.0/24,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,198.18.0.0/15,DIRECT,no-resolve
- IP-CIDR,198.51.100.0/24,DIRECT,no-resolve
- IP-CIDR,203.0.113.0/24,DIRECT,no-resolve
- IP-CIDR,224.0.0.0/3,DIRECT,no-resolve
- IP-CIDR,::/127,DIRECT,no-resolve
- IP-CIDR,fc00::/7,DIRECT,no-resolve
- IP-CIDR,fe80::/10,DIRECT,no-resolve
- IP-CIDR,ff00::/8,DIRECT,no-resolve
- RULE-SET,private_domain,DIRECT,no-resolve
- DOMAIN-SUFFIX,services.googleapis.cn,三毛机场
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,三毛机场
- DOMAIN,safebrowsing.urlsec.qq.com,DIRECT
- DOMAIN,safebrowsing.googleapis.com,DIRECT
- DOMAIN,developer.apple.com,三毛机场
- DOMAIN-SUFFIX,digicert.com,三毛机场
- DOMAIN,ocsp.apple.com,三毛机场
- DOMAIN,ocsp.comodoca.com,三毛机场
- DOMAIN,ocsp.usertrust.com,三毛机场
- DOMAIN,ocsp.sectigo.com,三毛机场
- DOMAIN,ocsp.verisign.net,三毛机场
- DOMAIN-SUFFIX,apple-dns.net,三毛机场
- DOMAIN,testflight.apple.com,三毛机场
- DOMAIN,sandbox.itunes.apple.com,三毛机场
- DOMAIN,itunes.apple.com,三毛机场
- DOMAIN-SUFFIX,apps.apple.com,三毛机场
- DOMAIN-SUFFIX,blobstore.apple.com,三毛机场
- DOMAIN,cvws.icloud-content.com,三毛机场
- DOMAIN-SUFFIX,mzstatic.com,DIRECT
- DOMAIN-SUFFIX,itunes.apple.com,DIRECT
- DOMAIN-SUFFIX,icloud.com,DIRECT
- DOMAIN-SUFFIX,icloud-content.com,DIRECT
- DOMAIN-SUFFIX,me.com,DIRECT
- DOMAIN-SUFFIX,aaplimg.com,DIRECT
- DOMAIN-SUFFIX,cdn20.com,DIRECT
- DOMAIN-SUFFIX,cdn-apple.com,DIRECT
- DOMAIN-SUFFIX,akadns.net,DIRECT
- DOMAIN-SUFFIX,akamaiedge.net,DIRECT
- DOMAIN-SUFFIX,edgekey.net,DIRECT
- DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
- DOMAIN-SUFFIX,mwcname.com,DIRECT
- DOMAIN-SUFFIX,apple.com,DIRECT
- DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
- DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
- RULE-SET,geolocation-!cn,三毛机场,no-resolve
- RULE-SET,cn_domain,DIRECT,no-resolve
- AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
- IP-CIDR,221.228.32.13/32,三毛机场
- RULE-SET,google_ip,三毛机场
- RULE-SET,netflix_ip,三毛机场
- RULE-SET,telegram_ip,三毛机场
- RULE-SET,twitter_ip,三毛机场
- RULE-SET,cn_ip,DIRECT
- MATCH,三毛机场
rule-anchor:
  ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
  domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
rule-providers:
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs
  google_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs
  netflix_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs
  twitter_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs
